### PR TITLE
Add NDK support

### PR DESCRIPTION
**Pull request by stkerr**

### CODE REVIEW

**Comment by carlossg** [comment]
Thanks @stkerr. There are some lint problems, can you fix them, and add some tests?

**Comment by stkerr** [comment]
I ran puppet-lint (http://puppet-lint.com/) to find and fix some errors, I assume that is the lint tool you were referring to?

**Comment by carlossg** [comment]
yes, that's puppet-lint

About the tests, can you create something like the sdk class test?
https://github.com/maestrodev/puppet-android/blob/master/spec/classes/sdk_spec.rb

**Comment by stkerr** [comment]
Can you point me to some resources on how to write a good one? I've never done an Rspec test before and want to make sure I do a good job of it.

**Comment by carlossg** [comment]
Something simple like sdk_spec will do, more detail is in https://github.com/rodjek/rspec-puppet

**Comment by stkerr** [comment]
I'm having a hard time picking up the RSpec stuff and also fairly short on time recently. Would it be possible for someone else to write the RSpec test for the android::ndk class? I can make fixes to the android::ndk class but the RSpec seems like a lot of black magic to me.

**Pull request merged**
