### PR TITLE
Fix ia32-libs package dependency for Debian Jessie.

### PR DESCRIPTION
**Pull request by gildor478**

### CODE REVIEW

**Comment by nerzhul** [comment]
please merge this commit, else this module cannot be used with Debian 8

**Comment by carlossg** [comment]
the build is failing, can you fix it?

**Comment by nerzhul** [comment]
@carlossg  seems now it's okay

**Comment by gildor478** [comment]
ping ? can you merge this commit ?

**Comment by func0der** [comment]
Okay. When this is going to be released? It has been merged for two years now, but there was no new tag or a new entry on forge.puppet.com.

@carlossg @MaestroDev

**Comment by carlossg** [comment]
If you haven't figured it out yet this project is not maintained

**Comment by func0der** [comment]
Could you hand it over to someone else and/or give someone permission to maintain it.
Or at least change the README to mention that development has been discontinued?

**Pull request merged**
