### PR TITLE
Add package revision parameter, fix NDK install, check package exists

### LINKED ISSUE #26: Is there a way to upgrade tools and platform-tools?
I can't seem to figure out how to get puppet to upgrade the android platform tools to the latest version.

### LINKED ISSUE #34: Found a way to update packages to certain revision, pull request?
Hi!

I've been using your module for a while to support a dozen Linux build servers with Android SDK.

We have some legacy apps to support, so we need different versions of build tools, and the developers would often ask me to update this or that package (but not all of them).

To keep track on this, I've tweaked package.pp adding `$revision` parameter and an unless for exec:
    unless  => "grep 'Pkg.Revision=${revision}' ${creates}/source.properties",

So my Android SDK definition looks a bit noisier:

      android::platform { 'android-13': revision => '1' }
      android::platform { 'android-12': revision => '3' }
      android::platform { 'android-11': revision => '2' }
      android::platform { 'android-10': revision => '2' }
    
      android::extra { 'extra-android-m2repository':              revision => '14.0.0' }
      android::extra { 'extra-android-support':                   revision => '22.1.1' }
      android::extra { 'extra-google-admob_ads_sdk':              revision => '11.0.0' }
      android::extra { 'extra-google-analytics_sdk_v2':           revision => '3.0.0' }
      android::extra { 'extra-google-gcm':                        revision => '3.0.0' }

It also requires some familiarity with command-line package manager, but it made the whole process A LOT easier for me as a sysadmin.

It adds one extra grep per package defined, but with around three dozens of these I'm having roughly the same agent run time as without them.

Should I create a pull request for that or does it make things unnecessarily complicated?

### LINKED ISSUE #36: Return an error on failed packages - not working again, apparently.
This is probably a regression from https://github.com/maestrodev/puppet-android/pull/24

This was fixed in da769379e476a052b509b1ff5523f8f44e01302f  but I believe 2701669bbc9d614af7cd48136deb1551ce424feb caused the same problem.

### LINKED ISSUE #43: NDK ownership
Android::ndk sets the ownership (user and group) to android::user and android::group for the downloaded installer executable, but the actual installed NDK ends up still owned root:root and un-executable by other users.

### PR DESCRIPTION
**Pull request by jamiesnape**
1. Add `revision` parameter to `android::package` and related defines:
   1. `present` ensures some revision of the package is installed and does not upgrade the package when a new version is available.
   2. `'n'` ensures that if revision 'n' of the package is installed, then it is not upgraded. Due to limitations of the android tool, if revision 'n' is not installed, then the latest revision will be installed. Fixes #34.
   3. `latest` ensures that the latest revision of the package is installed and upgrades the package when a new version available. Fixes #26.
2. Ensure the NDK is installed by `$android::user` by running the installer as `$android::user`. Fixes #43.
3. Check that a package exists before trying to install it. Fixes #36.
4. Lint and documentation.

(Tested on OS X 10.11, Debian 7, and Ubuntu 14.04, 15.10)

### CODE REVIEW

**Comment by jamiesnape** [comment]
@carlossg PTAL. We have been using this successfully for over a month, so it is well tested.

**Comment by mihelich** [comment]
@carlossg what needs to happen to get these multiple fixes merged? It looks like others are trying to build off this branch (#46), or apply similar platform fixes (#49, #50).

**Comment by carlossg** [comment]
It'd be best if somebody forks this repo into @voxpupuli, as I'm not using puppet anymore.
 Tests are failing too

**Comment by jamiesnape** [comment]
The tests are failing before even running this change.

**Pull request closed without merging**
